site_name: PushBits

site_url: https://www.pushbits.io/docs/

nav:
    - Getting Started: index.md
    - User Guide: user-guide.md
    - Developer Guide: developer-guide.md

theme:
  name: material
  favicon: assets/favicon.ico
  logo: assets/logo.svg
  icon:
    repo: fontawesome/brands/github
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - toc.integrate
    - search.suggest
    - search.highlight
    - header.autohide

extra:
  homepage: https://www.pushbits.io/
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/eikendev

plugins:
  - search

repo_url: https://github.com/pushbits/server
repo_name: pushbits/server
edit_uri: ""
copyright: Copyright &copy; 2021 The PushBits Developers
